#!/usr/bin/env Rscript
# Generate publication figures for hypothalamic FC manuscript.
#
# Fig 1 — Neuron yield heatmap + stimulus protocol overview
# Fig 2 — Mixed-effects model estimates + CIs (node strength, CC, LE, hub)
# Fig 3 — Region-level connectivity matrix (Day/Night × Ongoing/LightON)
# Fig 4 — Hub stability (already generated by hub_stability.R)
# Fig 5 — GLMCC ↔ TE convergence on node strength
#
# Usage: Rscript src/r/make_figures.R

library(here)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)

dir.create(here("figures", "main"), showWarnings = FALSE, recursive = TRUE)

# ─── Fig 1: Neuron yield heatmap ───────────────────────────────────
cat("Generating Fig 1: neuron yield\n")

neurons <- read.csv(here("data", "processed", "neurons.csv"), stringsAsFactors = FALSE)

# Per-animal per-region counts
yield <- neurons %>%
  count(animal, region6) %>%
  tidyr::complete(animal, region6, fill = list(n = 0))

# Day/night assignment
daynight <- c(
  "day1" = "Day", "night1" = "Night", "night2" = "Night", "night3" = "Night",
  "night4" = "Night", "night5" = "Night", "day2" = "Day", "night6" = "Night",
  "night7" = "Night", "day3" = "Day", "day4" = "Day", "day5" = "Day",
  "day6" = "Day"
)
yield$day_night <- daynight[as.character(yield$animal)]
yield$animal <- factor(yield$animal, levels = c(
  "day1","night1","night2","night3","night4","night5",
  "day2","night6","night7","day3","day4","day5","day6"
))

p1 <- ggplot(yield, aes(x = region6, y = animal, fill = n)) +
  geom_tile(color = "white", linewidth = 0.5) +
  geom_text(aes(label = ifelse(n > 0, n, "")), size = 3, color = "white") +
  scale_fill_gradient(low = "#f7fbff", high = "#08519c", na.value = "grey90") +
  facet_wrap(~ day_night, ncol = 1, scales = "free_y") +
  labs(x = "Brain Region", y = "Animal",
       title = "Fig 1: Neuron yield per animal and region",
       fill = "Neurons") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(here("figures", "main", "fig1_yield.png"), p1, width = 8, height = 7, dpi = 150)
cat("  fig1_yield.png\n")

# ─── Fig 2: Mixed-effects interaction estimates ──────────────────────
cat("Generating Fig 2: LME interaction estimates\n")

stats_file <- here("results", "stats_first_level_glmcc.csv")
if (file.exists(stats_file)) {
  stats_df <- read.csv(stats_file, stringsAsFactors = FALSE)

  # Extract interaction terms only: conditionlightON:regionXX
  interactions <- stats_df[
    grepl("^conditionlightON:region", stats_df$term) &
    !grepl("^ANOVA_", stats_df$term) &
    !is.na(stats_df$std_error) & stats_df$std_error > 0,
  ]

  if (nrow(interactions) > 0) {
    # Parse region name from term
    interactions$region <- gsub("conditionlightON:region", "", interactions$term)
    interactions$region <- factor(interactions$region,
      levels = rev(unique(interactions$region)))  # reverse for forest plot order

    # Add significance stars
    interactions$sig <- ""
    interactions$sig[interactions$p_value < 0.05]  <- "*"
    interactions$sig[interactions$p_value < 0.01]  <- "**"
    interactions$sig[interactions$p_value < 0.001] <- "***"

    # Add metric label with ANOVA p-value if available
    anova_rows <- stats_df[grepl("ANOVA_condition:region", stats_df$term), ]
    metric_labels <- c(
      node_strength = "Node Strength",
      clustering_coefficient = "Clustering Coeff",
      local_efficiency = "Local Efficiency",
      hub_score = "Hub Score"
    )
    interactions$metric_label <- metric_labels[interactions$metric]

    # Add ANOVA p-value annotation per metric
    for (m in unique(interactions$metric)) {
      arow <- anova_rows[anova_rows$metric == m, ]
      if (nrow(arow) > 0) {
        pval <- arow$p_value[1]
        pstr <- if (pval < 0.001) sprintf("p=%.2e", pval)
                else sprintf("p=%.4f", pval)
        interactions$metric_label[interactions$metric == m] <-
          paste0(interactions$metric_label[interactions$metric == m],
                 "  (interaction ", pstr, ")")
      }
    }

    # Color by direction: blue = lightON increases, red = lightON decreases
    interactions$direction <- ifelse(interactions$estimate > 0, "increase", "decrease")

    p2 <- ggplot(interactions,
           aes(x = estimate, y = region, color = direction)) +
      geom_vline(xintercept = 0, linetype = "dashed", color = "grey50", linewidth = 0.4) +
      geom_point(size = 3) +
      geom_errorbar(aes(xmin = estimate - 1.96 * std_error,
                         xmax = estimate + 1.96 * std_error),
                     height = 0.2, linewidth = 1) +
      geom_text(aes(label = sig, x = estimate + sign(estimate) *
                      (1.96 * std_error + max(abs(estimate)) * 0.08)),
                size = 4, show.legend = FALSE) +
      scale_color_manual(
        values = c(increase = "#2166ac", decrease = "#b2182b"),
        labels = c(increase = "LightON > Ongoing", decrease = "LightON < Ongoing"),
        name = "LightON effect"
      ) +
      facet_wrap(~ metric_label, scales = "free_x", ncol = 2) +
      labs(
        x = "Interaction estimate (LightON:Region) ± 95% CI",
        y = "Hypothalamic Region",
        title = "Fig 2: Light-ON effect on functional connectivity varies by region",
        subtitle = "lmer(metric ~ condition * region + (1 | animal/neuron)) — GLMCC, CCG-validated edges",
        caption = "Estimates show how LightON effect differs from baseline (VM-thalamus + Ongoing).\n* p<0.05  ** p<0.01  *** p<0.001"
      ) +
      theme_minimal(base_size = 12) +
      theme(
        strip.text = element_text(face = "bold", size = 11),
        panel.spacing = unit(1.5, "lines"),
        legend.position = "bottom",
        plot.caption = element_text(hjust = 0, size = 9, color = "grey40")
      )

    ggsave(here("figures", "main", "fig2_lme.png"), p2,
           width = 12, height = 8, dpi = 150)
    cat("  fig2_lme.png\n")
  } else {
    cat("  (skipped — no interaction terms in stats file)\n")
  }
} else {
  cat("  (skipped — no stats file)\n")
}

# ─── Fig 3: Region-level connectivity ──────────────────────────────
cat("Generating Fig 3: region connectivity\n")

# Aggregate density across animals for each condition
animals <- c("day1","night1","night2","night3","night4","night5",
             "day2","night6","night7","day3","day4","day5","day6")
daynight <- c(
  "day1"="D","night1"="N","night2"="N","night3"="N",
  "night4"="N","night5"="N","day2"="D","night6"="N",
  "night7"="N","day3"="D","day4"="D","day5"="D","day6"="D"
)

all_dens <- data.frame()
for (a in animals) {
  fp <- here("results", "glmcc", paste0("density_long_", a, "_lightON.csv"))
  if (file.exists(fp)) {
    df <- read.csv(fp, stringsAsFactors = FALSE)
    df$day_night <- daynight[a]
    all_dens <- rbind(all_dens, df)
  }
}

if (nrow(all_dens) > 0) {
  # Mean density per region pair × condition × day_night
  mean_dens <- all_dens %>%
    group_by(source, target, day_night) %>%
    summarise(density = mean(density, na.rm = TRUE), .groups = "drop")

  p3 <- ggplot(mean_dens, aes(x = source, y = target, fill = density)) +
    geom_tile(color = "grey80") +
    scale_fill_gradient(low = "white", high = "#cb181d", limits = c(0, max(mean_dens$density, 0.1))) +
    facet_wrap(~ day_night) +
    labs(x = "Source Region", y = "Target Region",
         title = "Fig 3: Region-level connectivity (lightON, GLMCC-validated)",
         subtitle = "Mean connection density across animals",
         fill = "Density") +
    theme_minimal(base_size = 11) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave(here("figures", "main", "fig3_region_conn.png"), p3, width = 10, height = 8, dpi = 150)
  cat("  fig3_region_conn.png\n")
} else {
  cat("  (skipped — no density data)\n")
}

# ─── Fig 5: GLMCC ↔ TE convergence ─────────────────────────────────
cat("Generating Fig 5: GLMCC vs TE convergence\n")

convergence <- data.frame()
for (a in animals) {
  g_path <- here("results", "glmcc", paste0("metrics_", a, "_lightON.csv"))
  t_path <- here("results", "te", paste0("result_te_", a, "_evoked.csv"))
  if (!file.exists(g_path) || !file.exists(t_path)) next

  g_met <- read.csv(g_path, stringsAsFactors = FALSE)
  if (!"node_strength" %in% colnames(g_met)) next

  t_mat <- as.matrix(read.csv(t_path, header = FALSE))
  if (nrow(t_mat) != nrow(g_met)) next

  te_strength <- rowSums(t_mat)
  gl_strength <- g_met$node_strength

  rho_sp <- suppressWarnings(cor(gl_strength, te_strength, method = "spearman"))
  rho_pe <- suppressWarnings(cor(gl_strength, te_strength, method = "pearson"))

  convergence <- rbind(convergence, data.frame(
    animal = a,
    spearman = rho_sp,
    pearson = rho_pe,
    n_neurons = nrow(g_met),
    row.names = NULL
  ))
}

if (nrow(convergence) > 0) {
  conv_long <- convergence %>%
    pivot_longer(c(spearman, pearson), names_to = "method", values_to = "rho")

  p5 <- ggplot(conv_long, aes(x = reorder(animal, rho, na.rm = TRUE), y = rho, fill = method)) +
    geom_col(position = position_dodge(width = 0.7), width = 0.6) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    scale_fill_manual(values = c(spearman = "#3182bd", pearson = "#e6550d")) +
    labs(x = "Animal", y = "Correlation (GLMCC strength vs TE strength)",
         title = "Fig 5: Convergent validity GLMCC ↔ TE",
         subtitle = paste0("Mean Spearman rho = ", round(mean(convergence$spearman, na.rm = TRUE), 3),
                           ", Mean Pearson r = ", round(mean(convergence$pearson, na.rm = TRUE), 3)),
         fill = "Method") +
    theme_minimal(base_size = 12) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave(here("figures", "main", "fig5_convergence.png"), p5, width = 9, height = 5, dpi = 150)
  cat("  fig5_convergence.png\n")
} else {
  cat("  (skipped — no convergence data)\n")
}

cat("\nAll figures generated in figures/main/\n")
