#!/usr/bin/env Rscript
# Generate publication figures for hypothalamic FC manuscript.
#
# Fig 1 — Neuron yield heatmap + stimulus protocol overview
# Fig 2 — Mixed-effects model estimates + CIs (node strength, CC, LE, hub)
# Fig 3 — Region-level connectivity matrix (Day/Night × Ongoing/LightON)
# Fig 4 — Hub stability (already generated by hub_stability.R)
# Fig 5 — GLMCC ↔ TE convergence on node strength
#
# Usage: Rscript src/r/make_figures.R

library(here)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)

dir.create(here("figures", "main"), showWarnings = FALSE, recursive = TRUE)

# ─── Fig 1: Neuron yield heatmap ───────────────────────────────────
cat("Generating Fig 1: neuron yield\n")

neurons <- read.csv(here("data", "processed", "neurons.csv"), stringsAsFactors = FALSE)

# Per-animal per-region counts
yield <- neurons %>%
  count(animal, region6) %>%
  tidyr::complete(animal, region6, fill = list(n = 0))

# Day/night assignment
daynight <- c(
  "171019" = "Day", "171207" = "Night", "171208" = "Night", "171213" = "Night",
  "180110" = "Night", "180111" = "Night", "180131" = "Day", "180221" = "Night",
  "180228" = "Night", "180302" = "Day", "180419" = "Day", "180420" = "Day",
  "180423" = "Day"
)
yield$day_night <- daynight[as.character(yield$animal)]
yield$animal <- factor(yield$animal, levels = c(
  "171019","171207","171208","171213","180110","180111",
  "180131","180221","180228","180302","180419","180420","180423"
))

p1 <- ggplot(yield, aes(x = region6, y = animal, fill = n)) +
  geom_tile(color = "white", linewidth = 0.5) +
  geom_text(aes(label = ifelse(n > 0, n, "")), size = 3, color = "white") +
  scale_fill_gradient(low = "#f7fbff", high = "#08519c", na.value = "grey90") +
  facet_wrap(~ day_night, ncol = 1, scales = "free_y") +
  labs(x = "Brain Region", y = "Animal",
       title = "Fig 1: Neuron yield per animal and region",
       fill = "Neurons") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(here("figures", "main", "fig1_yield.png"), p1, width = 8, height = 7, dpi = 150)
cat("  fig1_yield.png\n")

# ─── Fig 2: Mixed-effects estimates ─────────────────────────────────
cat("Generating Fig 2: LME model estimates\n")

stats_file <- here("results", "stats_first_level_glmcc.csv")
if (file.exists(stats_file)) {
  stats_df <- read.csv(stats_file, stringsAsFactors = FALSE)
  
  # Filter to fixed effects (exclude ANOVA rows)
  fixed <- stats_df[!grepl("^ANOVA_", stats_df$term), ]
  fixed <- fixed[!is.na(fixed$std_error) & fixed$std_error > 0, ]
  
  p2 <- ggplot(fixed, aes(x = metric, y = estimate, color = term)) +
    geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
    geom_point(position = position_dodge(width = 0.5), size = 3) +
    geom_errorbar(
      aes(ymin = estimate - 1.96 * std_error,
          ymax = estimate + 1.96 * std_error),
      width = 0.2,
      position = position_dodge(width = 0.5)
    ) +
    scale_color_brewer(palette = "Set1") +
    labs(x = "Graph Metric", y = "Fixed Effect Estimate ± 95% CI",
         title = "Fig 2: Mixed-effects model estimates (GLMCC)",
         subtitle = "lmer(metric ~ condition + (1 | animal/neuron))") +
    coord_flip() +
    theme_minimal(base_size = 13)

  ggsave(here("figures", "main", "fig2_lme.png"), p2, width = 10, height = 5, dpi = 150)
  cat("  fig2_lme.png\n")
} else {
  cat("  (skipped — no stats file)\n")
}

# ─── Fig 3: Region-level connectivity ──────────────────────────────
cat("Generating Fig 3: region connectivity\n")

# Aggregate density across animals for each condition
animals <- c("171019","171207","171208","171213","180110","180111",
             "180131","180221","180228","180302","180419","180420","180423")
daynight <- c(
  "171019"="D","171207"="N","171208"="N","171213"="N",
  "180110"="N","180111"="N","180131"="D","180221"="N",
  "180228"="N","180302"="D","180419"="D","180420"="D","180423"="D"
)

all_dens <- data.frame()
for (a in animals) {
  fp <- here("results", "glmcc", paste0("density_long_", a, "_lightON.csv"))
  if (file.exists(fp)) {
    df <- read.csv(fp, stringsAsFactors = FALSE)
    df$day_night <- daynight[a]
    all_dens <- rbind(all_dens, df)
  }
}

if (nrow(all_dens) > 0) {
  # Mean density per region pair × condition × day_night
  mean_dens <- all_dens %>%
    group_by(source, target, day_night) %>%
    summarise(density = mean(density, na.rm = TRUE), .groups = "drop")

  p3 <- ggplot(mean_dens, aes(x = source, y = target, fill = density)) +
    geom_tile(color = "grey80") +
    scale_fill_gradient(low = "white", high = "#cb181d", limits = c(0, max(mean_dens$density, 0.1))) +
    facet_wrap(~ day_night) +
    labs(x = "Source Region", y = "Target Region",
         title = "Fig 3: Region-level connectivity (lightON, GLMCC-validated)",
         subtitle = "Mean connection density across animals",
         fill = "Density") +
    theme_minimal(base_size = 11) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave(here("figures", "main", "fig3_region_conn.png"), p3, width = 10, height = 8, dpi = 150)
  cat("  fig3_region_conn.png\n")
} else {
  cat("  (skipped — no density data)\n")
}

# ─── Fig 5: GLMCC ↔ TE convergence ─────────────────────────────────
cat("Generating Fig 5: GLMCC vs TE convergence\n")

convergence <- data.frame()
for (a in animals) {
  g_path <- here("results", "glmcc", paste0("metrics_", a, "_lightON.csv"))
  t_path <- here("results", "te", paste0("result_te_", a, "_evoked.csv"))
  if (!file.exists(g_path) || !file.exists(t_path)) next

  g_met <- read.csv(g_path, stringsAsFactors = FALSE)
  if (!"node_strength" %in% colnames(g_met)) next

  t_mat <- as.matrix(read.csv(t_path, header = FALSE))
  if (nrow(t_mat) != nrow(g_met)) next

  te_strength <- rowSums(t_mat)
  gl_strength <- g_met$node_strength

  rho_sp <- suppressWarnings(cor(gl_strength, te_strength, method = "spearman"))
  rho_pe <- suppressWarnings(cor(gl_strength, te_strength, method = "pearson"))

  convergence <- rbind(convergence, data.frame(
    animal = a,
    spearman = rho_sp,
    pearson = rho_pe,
    n_neurons = nrow(g_met),
    row.names = NULL
  ))
}

if (nrow(convergence) > 0) {
  conv_long <- convergence %>%
    pivot_longer(c(spearman, pearson), names_to = "method", values_to = "rho")

  p5 <- ggplot(conv_long, aes(x = reorder(animal, rho, na.rm = TRUE), y = rho, fill = method)) +
    geom_col(position = position_dodge(width = 0.7), width = 0.6) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    scale_fill_manual(values = c(spearman = "#3182bd", pearson = "#e6550d")) +
    labs(x = "Animal", y = "Correlation (GLMCC strength vs TE strength)",
         title = "Fig 5: Convergent validity GLMCC ↔ TE",
         subtitle = paste0("Mean Spearman rho = ", round(mean(convergence$spearman, na.rm = TRUE), 3),
                           ", Mean Pearson r = ", round(mean(convergence$pearson, na.rm = TRUE), 3)),
         fill = "Method") +
    theme_minimal(base_size = 12) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave(here("figures", "main", "fig5_convergence.png"), p5, width = 9, height = 5, dpi = 150)
  cat("  fig5_convergence.png\n")
} else {
  cat("  (skipped — no convergence data)\n")
}

cat("\nAll figures generated in figures/main/\n")
