#!/usr/bin/env python3
"""Assemble a duty-cycle-matched estimator tree for the corrected LME.

results/glmcc_dc/ mirrors the layout the R scripts expect, but its two conditions are
matched on observation structure:

  validated_adj_{animal}_lightON.csv  raw GLMCC on the native lightON epoch (~10% duty)
  validated_adj_{animal}_ongoing.csv  raw GLMCC on ongoing gapped to the true stimulus
                                      windows shifted +45 s into the light-off interval

Two deliberate departures from the original pipeline, both documented in
reports/glmcc_sign_asymmetry_diagnosis.md:

1. Weights are NOT surrogate-validated. shuffle-ISI surrogates are invalid on a gapped
   train -- shuffling intervals scatters the ~80 s inter-window gaps and destroys the
   structure being matched. The validation also removed only 0.5% of edges, so omitting
   it costs little and avoids a step that behaves differently on gapped vs continuous data.
2. The "ongoing" slot holds gapped data, so that the condition contrast is not confounded
   by duty cycle. It is NOT the native ongoing recording.
"""

import csv
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src" / "py"))
from validate_edges import RankMismatchError, _align_to_units  # noqa: E402
from validate_ccg import load_real_spike_times  # noqa: E402

SRC = PROJECT_ROOT / "results" / "glmcc"
DST = PROJECT_ROOT / "results" / "glmcc_dc"
ANIMALS = ["day1", "day2", "day3", "day4", "day5", "day6",
           "night1", "night2", "night3", "night4", "night5", "night6", "night7"]


def neuron_counts() -> dict:
    counts: dict[str, int] = {}
    with (PROJECT_ROOT / "data" / "processed" / "neurons.csv").open() as fh:
        for row in csv.DictReader(fh):
            counts[row["animal"]] = counts.get(row["animal"], 0) + 1
    return counts


def main() -> int:
    if DST.exists():
        shutil.rmtree(DST)
    DST.mkdir(parents=True)
    counts = neuron_counts()
    rows = []

    for animal in ANIMALS:
        want = counts[animal]
        row = {"animal": animal, "n_expected": want, "lightON": "", "ongoing": "", "note": ""}

        # lightON: raw GLMCC on the native epoch, realigned if units were dropped.
        src = SRC / f"adj_{animal}_lightON.csv"
        if src.exists():
            adj = np.loadtxt(src, delimiter=",", ndmin=2)
            try:
                times = load_real_spike_times(animal, "lightON")
                adj = _align_to_units(adj, times, src)
                if adj.shape[0] != want:
                    raise RankMismatchError(f"{adj.shape[0]} != {want} after alignment")
                np.savetxt(DST / f"validated_adj_{animal}_lightON.csv", adj,
                           delimiter=",", fmt="%.6f")
                row["lightON"] = adj.shape[0]
            except (RankMismatchError, Exception) as exc:  # noqa: BLE001
                row["note"] = f"lightON excluded: {str(exc)[:110]}"
        else:
            row["note"] = "lightON missing"

        # ongoing slot: duty-cycle-matched gapped data.
        src = SRC / f"adj_{animal}_ongoing_aligned.csv"
        if src.exists():
            adj = np.loadtxt(src, delimiter=",", ndmin=2)
            if adj.shape[0] == want:
                np.savetxt(DST / f"validated_adj_{animal}_ongoing.csv", adj,
                           delimiter=",", fmt="%.6f")
                row["ongoing"] = adj.shape[0]
            else:
                row["note"] += f" | ongoing rank {adj.shape[0]} != {want}"
        else:
            row["note"] += " | ongoing_aligned missing"

        rows.append(row)
        print(f"  {animal:8s} lightON={str(row['lightON']):>4s} ongoing={str(row['ongoing']):>4s} "
              f"{row['note']}")

    (DST / "README.md").write_text(
        "# Duty-cycle-matched GLMCC matrices\n\n"
        "`lightON` is the native stimulus epoch (~10% duty cycle). `ongoing` is the ongoing\n"
        "recording gapped to the true stimulus windows shifted +45 s into the light-off\n"
        "interval, so both conditions share the observation structure that biases GLMCC's\n"
        "baseline.\n\n"
        "Weights are raw GLMCC, NOT surrogate-validated: shuffle-ISI surrogates are invalid\n"
        "on gapped trains, and the validation removed only 0.5% of edges.\n\n"
        "See reports/glmcc_sign_asymmetry_diagnosis.md. Generated by\n"
        "scripts/assemble_dutycycle_matched.py.\n"
        f"\nGenerated {datetime.now(timezone.utc).isoformat()}\n")

    out = PROJECT_ROOT / "results" / "dutycycle_matched_inputs.csv"
    with out.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["animal", "n_expected", "lightON", "ongoing", "note"])
        w.writeheader()
        w.writerows(rows)

    paired = sum(1 for r in rows if r["lightON"] and r["ongoing"])
    print(f"\n{paired}/{len(rows)} animals have both conditions. Inputs: {DST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
